# On the top line we set the most recent version of Docker Compose 
# which is currently 3.9
version: '3.9'

# Specify which services (or containers) we want to have running 
# within our Docker host.
services:

  client:
    build: ./client
    # container_name: client
    depends_on:
      - api
    image: react_image
    ports:
      - 3000:3000
    restart: "on-failure"
    volumes:
      - ./client:/code/client
      - node-modules:/code/client/node_modules

  api:
    build: ./api
    command: sh -c 'python manage.py makemigrations &&
                    python manage.py migrate --no-input &&
                    python manage.py collectstatic --no-input &&
                    gunicorn main.wsgi:application --bind 0.0.0.0:8000'
    depends_on:
      - db
    env_file:
      - ./api/.env
    image: django_image
    ports:
      - 8000:8000
    restart: "on-failure"

    volumes:
      # The volumes mount automatically syncs the Docker filesystem 
      # with our local computer's filesystem. This if we make a change 
      # to the code within Docker it will automatically be synced with 
      # the local filesystem.
      - ./api:/code/api/
      - static_volume:/code/static/

  db:
    env_file:
      - ./api/.env
    image: postgres
    ports:
      - 5432:5432
    restart: "on-failure"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
      build: ./nginx
      depends_on:
        - api
        - client
      image: nginx_image
      ports:
        - 80:80
        - 81:81
      restart: "on-failure"
      volumes:
        - static_volume:/code/static

  # to start only jenkins service
  # docker compose up jenkins
  jenkins:
      image: jenkins/jenkins:lts
      privileged: true
      user: root
      ports:
        - 8080:8080
        # - 50000:50000
      container_name: jenkins
      volumes:
        # - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
        - jenkins_home:/var/jenkins_home
        # - /var/run/docker.sock:/var/run/docker.sock
        # - ./jenkins/var/run/docker.sock:/var/run/docker.sock

# to find the initial password in a log file
# docker logs jenkins | less
# docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword

volumes:
  node-modules:
  postgres_data:
  static_volume:
  jenkins_home:
